language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: QBuD6P9ZOAbwfXYzJVgQawkBiKXfpg0xmoVVii35Bk4FMTTtHFcV0NHfIBQ30vY7GMa9tvibPMIgk2QCBeyN08w9J1fOkaoU/CuNXS1JPI6uJi3Pul9ZtZBbY10YFF6hl9QM7aNTuEeKLHp4CH5MuRGhvot+nJTTyDO4+Yhy395B0/elHgr/cY/QkoZkkxv5ntiNyatz0Ehqpr1mdGzDjiP2mJ54xXAAIKxmXXFcWLK/XInnt9AXG8nO3eVlYREW/13GlEG6MWcFfoHktciJVLZbRD36W9U5zmYsi4eGwKGYaKsLAm/mY7q0C2Tn5ddbNp2RHflAjzNWPRDNBuvTvBqX9RRhq2Eh/52OrLxPRtpOj+ZdiTPSTka1gQMlC/BeIKfP58VL3fdOl9Az414VHmMgqDt+wZVeWToH4mzGGnvDe8jDgqBl2bivGZYu+6rA6WtqH/aeMeZMarP4tNW7om/SANatGu8MYHl9QZcZp45TbSseLRxg7CU5COwgUTvWAXbXQKCN19dhQNT8kg8lP2Zex4gZZRsuRGVuA3F65lsR0fLTJSM0A+oiPD1wzLb9eZIeoeE1622BlaFS7veWZQJ8ERs58yfBktBzn/K36sfUvoarOqmeW0fjFILgV8y3vYEKjAkwmEIKYLeKaIqTdQ1ADihXereHJ6sthW8rWGg=
    on:
      branch: master
      tags: true
